services:
  agregator-dev:
    extends:
      file: docker-compose.yml
      service: agregator
    container_name: agregator-dev
    env_file:
      - ./docker/app.env
      - ./docker/app.dev.env
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: "1"
    command: flask run --host=0.0.0.0 --port=5050 --reload
    volumes:
      - ./agregator:/app/agregator
      - ./app.py:/app/app.py
      - ./models.py:/app/models.py
      - ./routes.py:/app/routes.py
      - ./static:/app/static
      - ./runtime_settings.json:/app/runtime_settings.json
      - ./library:/data
      - ./backups:/app/backups
      - ./logs:/app/logs
    restart: unless-stopped
