services:
  agregator:
    # Чтобы переопределить значения из docker/app.env, раскомментируй блок ниже и укажи нужные пары KEY: VALUE
    # environment:
    #   LMSTUDIO_API_BASE: http://host.docker.internal:1234/v1
    #   LMSTUDIO_MODEL: gpt-4o-mini
    #   LMSTUDIO_API_KEY: sk-....
    # Пример подключения дополнительной базы/каталогов
    # volumes:
    #   - ./db/catalogue.db:/app/catalogue.db
